import archiveManifest from "@/data/archive-manifest.json";
import type { ArchiveImage } from "@/types/archive";

type ArchiveManifest = {
  generatedAt: string;
  files: string[];
};

const manifest = archiveManifest as ArchiveManifest;

/**
 * Archive image list from `src/data/archive-manifest.json` (generated by
 * `npm run archive:manifest` or `prebuild`). Avoids `fs` on `public/archive`
 * so deploy bundles stay under Vercel’s serverless size limit.
 */
export function getArchiveImages(): ArchiveImage[] {
  return manifest.files.map((f, i) => {
    const base = f.replace(/\.[^.]+$/, "");
    return {
      src: `/archive/${f}`,
      label: base,
      index: i + 1,
    };
  });
}
